### ISSUE TITLE
Game Launcher

### ISSUE THREAD

**Issue by Andoryuuta** [ErupeServer/Erupe#2]
Erupe is currently being developed with a modified client that has GameGuard removed. Because this client cannot be redistributed, a public launcher needs to be made that will hook the unmodified client and disable GG after the binaries get unpacked in memory by ASProtect/ASPack.

I made a [frida script](https://gist.github.com/Andoryuuta/a51d9f79114d64946b9e0656cdc0a72e) to do this previously, but it was accidentally based on a frankenstein-esque TW/JP mixed client, so it would need to be fixed to work on the regular JP client.

It might be more appropriate to rewrite this in another language and also hook the windows host resolution APIs to avoid modifying the `hosts` file as well.

**Comment by jet082** [comment]
For what it's worth, I tried your script on an unmodified JP client. It worked well enough to get me past the launcher and the various menus. However, when I got 'in-game' (meaning in the hub world), GameGuard got triggered again. I am unsure why, but I believe it reloads the binary to memory or something possibly, thereby erasing the modification?

I ended up figuring out how to unpack and patch out GameGuard from the relevant dll and exe myself afterwards, so it was not a big deal as far as that is concerned, but if you wanted to do a dynamic python hook using frida or something, it is possible you'd need to re-patch out GameGuard at various transition points or something. These would not necessarily be that difficult to find and catch, depending on how things work. I can poke around and see what happens when I get a more reliable debugger...

**Comment by Andoryuuta** [comment]
I am working on a custom launcher which will replace the `mhf.exe` and `mhl.dll` binaries and directly load the main game library (`mhfo.dll`|`mhfo-hd.dll`).

This will have many benefits over the current launcher setup:
- Will not be constantly deleted by Windows Defender, as it will not be linked to any of the nProtect GG libraries which are picked up as malware.
- Host file modifications will no longer be needed (which removes the requirement for local administrator privileges)
- Easy multi-server support
- Remove legacy IE weirdness with the launcher (double click because of the bootstrap polyfills, iframes, etc)
- If extended to the TW client, then it could be used to properly determine the character encoding and language needed per-client (Shift-JIS vs Big5).


I'm still reverse engineering portions of the C struct that is passed around for this, however, I do already have a prototype which can launch the game/connect to a normal server without issues.

**Comment by R5GAMER** [comment]
I don't know if it can be useful but I created an .exe which allows to launch the game via the command prompt it directly executes the .py file (it includes running in admin mode) if you want I can give it to you, it is not detected by NOD32 for others antivirus I do not know.
What language do you use for all of this work ? I may be able to help with the development.
