### ISSUE TITLE
Quest bin info and Additions to ReadMe

### ISSUE THREAD

**Issue by jet082** [ErupeServer/Erupe#33]
I managed to get this entirely set up from a completely fresh Monster Hunter Frontier install. It took me the better part of three days (mostly to unpack the exe/dlls and then remove gameguard by hand. Learned a lot about reverse engineering and debugging/asm in the process), but I now have a character and I can walk around the hub. My friends can also connect and everything is fine.

However, I do not know where to get the quest .bin files. It sounds like, from the readme, that they should come packaged with the game. But I do not see them anywhere.

When I enter a quest I get the error message (on the server side):
```
Recovered from panic  open bin\quests\22031d0.bin: The system cannot find the file specified.
```

Assuming that I should have these files, where are they? Are they in the campaign/*.txb files and do I have to extract them, somehow? I have been playing around quite a bit with https://github.com/mhvuze/ReFrontier FrontierDataTool (as well as the main ReFrontier program) and I have not had luck finding them so far.

Additionally, for the ReadMe, it would be nice to specify that the server requires the creation of a "savedata" directory (I had to go digging in the code to figure out that related error).

**Comment by Andoryuuta** [comment]
Sorry if there was any confusion caused by the README. This project is not yet in a state where it can an be setup and used from the source alone.

The quest files were sent from the server and are not all included in the game. I do believe a specific subset of the quests are special cased by ID and included somewhere in the client files. However, from prior emails I've received, I'm not sure if those quests show up in the default quest list. I have never tracked down which ones / where they are stored exactly.

I do hope to make something to generate these quests from scratch in the future. However, for now, quests will not work unless you have saved the binaries sent from when the original servers were alive.



Thanks for letting me know about the savedata folder issue! That's definitely a bug. That folder is just a very hacked-together backup solution, as clients can very easily corrupt their own save files currently.

**Comment by Andoryuuta** [comment]
Pinning this issue for anybody else who has questions regarding the quest files.

**Comment by MgSpike** [comment]
If you have the quest files, please tell me first 10 bytes and size of the files.
I think the quest files have something to do with 'mhfinf.bin'.

**Comment by rhobiusvoid** [comment]
Has there been any successful attempts at generating one's own .bin files for quests? The "quest editor" that I've found is largely incomplete and doesn't generate anything and works more like a fancy quest viewer at the moment. There is of course a manual way to do this (apparently through 010) but there's probably something I'm missing.

That way we could thereotically provide our own 'test quest' files without having to step into a legal gray area with Capcom and archiving.
