### ISSUE TITLE
Some questions about multiplay

### ISSUE THREAD

**Issue by Guanzorm** [ErupeServer/Erupe#37]
Thanks to your works, I can play MHF again with my friends.
We rented a server and found some problems in multiplay:
1.I can only see one other player in the square.
2.After canceling a quest, this quest still remains on quest board.
3.The hunters road skill and my Gugu in the garden will be emptied when I close the game. 

I also have a idea about ravi movement, I will tell you on another issue.

**Comment by Malckyor** [comment]
From my tests I think that the reason for the quests still remains on the quest board is because the quest is not properly programmed. When you post a quest that was not inserted that will happen, when you post a quest that has some issue it will also happen, but when the quest is properly programmed that will not happen. Somehow I was able to fix my quests and that never happened again.

**Comment by Andoryuuta** [comment]
I have created two seperate issues to track these seperately. #43 and #44. The garden and hunters road are not yet implemented in the emulator, so no specific data from these will be saved.
