### ISSUE TITLE
Bug with Unk0 declaration

### ISSUE THREAD

**Issue by jet082** [ErupeServer/Erupe#38]
I get the error
```
server/channelserver/handlers.go:82:3: unknown field 'Unk0' in struct literal of type mhfpacket.MsgSysUpdateRight
```

This can be fixed by restoring the line: ``Unk0 uint32`` right before https://github.com/ErupeServer/Erupe/blob/548a6c0593a450b8848c2f04245fd974830bb487/network/mhfpacket/msg_sys_update_right.go#L40 which was removed in 548a6c0593a450b8848c2f04245fd974830bb487

**Comment by Andoryuuta** [comment]
Thanks for reporting this! I thought I had compiled and tested before pushing this, but I guess not...
(I really need to get the CI setup before I make any other changes)

If you want to fix this before I have time to push a change, you can update:
https://github.com/ErupeServer/Erupe/blob/master/server/channelserver/handlers.go#L82
to use `ClientRespAckHandle` instead of `Unk0`.
