### ISSUE TITLE
Additional Documentation for Server Setup Steps

### ISSUE THREAD

**Issue by theBusBoy** [ErupeServer/Erupe#40]
I've put together some additional information for server setup that I think could benefit potential users. It's fairly opinionated in the tools it uses, but if followed correctly it should AT LEAST have someone able to get a server running locally.

Link Edit: Going to move most of this information into a github project wiki page in order to make it closer to the project.
Pdf version of 2/6 instructions available here until fully moved: https://www.mediafire.com/file/luvqtsgnx6rjr9f/Setting_up_Erupe.pdf/file

Feel free to take any portions of this document and use them in any form whatsoever.

I call out specifically at the end that without quest and scenario files that users will be unable to actually participate in quests, so hopefully any "how do quests?!?!" questions will be directed at me in the comments of that document instead of you guys so you can focus on whatever it is you want to work on (not even specifically this, just hope to alleviate some unneeded messages in general).

I am also unable to test the final step of actually connecting with a client as I'm still dealing the GameGuard AsProtect issue, so if there's any willingness to help me out there I'd greatly appreciate it, but no worries if not.

**Comment by jet082** [comment]
You need to unpack the .exe and the .dll and patch out GameGuard. To unpack the .exe, I forget what I used, but I remember having to boot up a Windows XP virtual machine.

After you unpack and patch, it will report a virus, but this is not an issue. It's likely simply due to a bad checksum in the header (which I should get around to fixing myself).

Instructions on how to do this can be found, sorta, here: https://gist.github.com/Andoryuuta/a51d9f79114d64946b9e0656cdc0a72e

You may also simply need to run that script. I tried and got somewhere, but would always crash when going into the hub itself. Only after patching both files manually did it work for me. Now note that the script targets ``mhfo.dll``, but you may be using ``mhfo-hd.dll``. However, I believe the pattern is the same (though the location is not if I recall correctly). So just find the segment that needs patching in ``mhfo-hd.dll` yourself and you can do it manually pretty easily.

**Comment by jet082** [comment]
Also, users can absolutely do quests. There is a monster hunter frontier quest maker here - https://github.com/tlfmonster/MHF-QuestEditor.

Anyone can simply use this to make their own quests, share them with others, fight whatever they want, etc.

**Comment by Andoryuuta** [comment]
@theBusBoy Thanks for writing this up! As silly as it may sound, I'm going to intentionally leave the README/documentation as a vague mess for now, as I really don't want people to think this project is something that is actually in a usable state. This is the same reason the first line in the README is: `This project is in its infancy and has no reliable active developer, no documentation, and no support.`

@jet082 I might be wrong, but I don't believe Yuvi's quest editor ever implemented quest creation or saving edits, so I think it's more akin to a quest viewer currently.

**Comment by theBusBoy** [comment]
No worries at all, I figured it would be something useful enough for people willing to go through some headache and might attract a few more devs who could potentially help out. 

Thanks again for your role in making this in general. It's a nice distraction to play with frankly.

**Comment by Malckyor** [comment]
I'll share an alternative way for the Step 4 - Phase 2-3 and I think it is easier to follow and it's more straight foward, you just run CMD as admin and use these:

go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn/,direct 
go get -tags 'postgres' -u github.com/golang-migrate/migrate/v4/cmd/migrate/

set POSTGRESQL_URL=postgres://postgres:password@localhost:5432/erupe?sslmode=disable

You all know the rest.

**Comment by yuhi-dosei** [comment]
I followed the readme and pdf instructions to set up and run the erupe server.  
However, when I tried to login from the client, I got the following error  

"error": "pq: Relation\"users\" does not exist"  

![error](https://user-images.githubusercontent.com/37332703/108019234-1fa35780-705d-11eb-815c-1ab45ed8ec4c.PNG)  

Do I need to rewrite the table name or the schema name to resolve this?

**Comment by rockisch** [comment]
Just as a comment, was having issues when running the `no_gg_jp.py` script on the `Process.getModuleByName('mhfo.dll');` call. Checking the frida docs, `Module.load('mhfo.dll');` should do the same thing, and that fixed it for me.

Also had to change it to fix 'mhfo-hd.dll' instead of 'mhfo.dll', but apparently that's on a case by case basis.
