### ISSUE TITLE
not an issue just some questions

### ISSUE THREAD

**Issue by soulmizute** [ErupeServer/Erupe#50]
right so i have some questions that someone should be able to awnser for me:
1) would i need any software that isnt the launcher and would i need to rent a server
2) how should i get rid of gameguard because i looked at the issues and through the files in the launcher for something to get rid of gameguard and get to the launcher. im probably just really blind
3)do i need to do anything specific to get past the login screen and/or have as stated in question 1 any additional software

im putting this under issues because there isnt anything to put questions
thankyou

**Comment by ricochhet** [comment]
The last time I responded to your issue I provided a link, clearly you have not read through it, nor decided to look through the PDF linked in the other issue, because that would've answered your questions. 

Since you could apparently not find the linked PDF, I've linked it directly for you [here](https://www.mediafire.com/file/luvqtsgnx6rjr9f/Setting_up_Erupe.pdf/file). 

To answer your questions briefly anyway:
1. Yes, read the PDF, no you don't *need* another server.
2. The script to bypass GameGuard is linked in the PDF.

Again, I must reiterate, all of your questions are answered in the PDF, had you decided to bother, but you did not. If you for some reason cannot access the mediafire link. I have a copy [here](https://github.com/ricochhet/MHF-Quest-Resources/blob/98f311b0f78af2541be8559189fc699e12be566f/docs/guides/Setting%20up%20Erupe.pdf). If for some reason you don't know how to use a PDF, I've partially rewrote it to a markdown file you can easily view [here](https://github.com/ricochhet/MHF-Quest-Resources/blob/main/docs/guides/Erupe-Setup-Guide.md).

If you truly have questions that are not listed in any of the following resources, you need to be more specific.
